options:
  elasticsearch_cluster:
    type: string
    default: "openstack"
    description: "The name of the elasticsearch cluster"
  elasticsearch_curator_logstash_prune_days:
    type: int
    default: 60
    description: "The number of days before logstash logs deleted"
  elasticsearch_curator_elasticsearch_prune_days:
    type: int
    default: 30
    description: "The number of days before elasticsearch logs deleted"
  elasticsearch_http_port:
    type: int
    default: 9200
    description: "The listening port for HTTP"
  elasticsearch_tcp_port:
    type: int
    default: 9300
    description: "The listening ports for tcp/json eents"
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup
