---
- name: Restart Kibana
  service:
    name: kibana
    state: restarted
    pattern: kibana

- name: Restart Apache
  service:
    name: "{{ apache_service }}"
    state: restarted
    pattern: "{{ apache_service }}"

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
    pattern: haproxy
