- name: Create deb_package_path
  file:
    path: "{{ package_path }}"
    state: directory
  tags:
    - install

- name: Copy over generated package
  copy:
    src: "{{ package_path_host }}/{{ package_file }}"
    dest: "{{ package_path }}/{{ package_file }}"
  when: ansible_architecture != 'x86_64'
  tags:
    - install

- name: Download package x86
  get_url:
    url: "{{ download_url }}/{{ package_file_amd64 }}"
    dest: "{{ package_path }}"
    checksum: "{{ download_checksum_amd64 }}"
  when: ansible_architecture == 'x86_64'
  register: filebeat_download
  until: filebeat_download | success
  retries: 5
  delay: 2
  tags:
    - install

- name: Install generated filebeat deb package
  apt:
    deb: "{{ package_path }}/{{ package_file }}"
    state: present
  when: ansible_architecture != 'x86_64'
  register: install_deb
  until: install_deb|success
  retries: 5
  delay: 2
  tags:
    - install

- name: Install x86_64 filebeat deb package
  apt:
    deb: "{{ package_path }}/{{ package_file_amd64 }}"
    state: present
  when: ansible_architecture == 'x86_64'
  register: install_deb
  until: install_deb|success
  retries: 5
  delay: 2
  tags:
    - install

- name: Remove the package_path directory
  file:
    path: "{{ package_path }}"
    state: absent
  tags:
    - install

- name: Set Application version
  shell: "application-version-set {{ filebeat_version }}"
  tags:
    - install
