options:
  filename:
    default: 'mysql.yml'
    type: string
    description: |
      Name of filebeat configuration file to create in /etc/filebeat/conf
  paths:
    default: "['/var/log/mysql/*.log']"
    type: string
    description: |
      A list of glob-based paths that should be crawled and fetched. All
      patterns supported by Golang Glob are also supported here. Filebeat
      starts a harvester for each file that it finds under the specified paths.
      You can specify one path per line. Each line begins with a dash (-).
  tags:
    default: "['mysql', 'infrastructure']"
    type: string
    description: |
      A list of tags that the Beat includes in the tags field of each published
      event. Tags make it easy to select specific events in Kibana or apply
      conditional filtering in Logstash. These tags will be appended to the list
      of tags specified in the general configuration.
  multiline_pattern:
    default: '^([^0-9W]|$)'
    type: string
    description: Specifies the regular expression pattern to match
  multiline_negate:
    default: false
    type: boolean
    description: Defines whether the pattern is negated. 
  multiline_match:
    default: after
    type: string
    description: Specifies how Filebeat combines matching lines into an event
  multiline_max_lines:
    default: 500
    type: int
    description: |
      The maximum number of lines that can be combined into one event. If the
      multiline message contains more than max_lines, any additional lines are
      discarded.
  multiline_timeout:
    default: 5s
    type: string
    description: |
      After the specified timeout, Filebeat sends the multiline event even if no
      new pattern is found to start a new event. The default is 5s. 
  encoding:
    default: utf-8
    type: string
    description: |
      The file encoding to use for reading files that contain international
      characters. See the encoding names recommended by the W3C for use in 
      HTML5: https://www.w3.org/TR/encoding/
  exclude_lines:
    default:
    type: string
    description: |
      A list of regular expressions to match the lines that you want Filebeat
      to exclude If multiline is also specified, each multiline message is
      combined into a single line before the lines are filtered by
      exclude_lines.
  include_lines:
    default:
    type: string
    description: |
      A list of regular expressions to match the lines that you want Filebeat
      to include. Filebeat exports only the lines that match a regular
      expression in the list. By default, all lines are exported. If multiline
      is also specified, each multiline message is combined into a single line
      before the lines are filtered by include_lines. If both include_lines and
      exclude_lines are defined, Filebeat executes include_lines first and then
      executes exclude_lines.
  exclude_files:
    default:
    type: string
    description: |
      A list of regular expressions to match the files that you want Filebeat to
      ignore. By default no files are excluded.
