---
- name: installs prereq packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kibana_pre_packages }}"
  register: install_preq
  until: install_preq|success
  retries: 5
  delay: 2
  tags:
    - install
