---
- name: create self-signed SSL cert
  command: >
    openssl req -new -nodes -x509 -subj
    "/C=US/ST=Texas/L=San Antonio/O=IT/CN={{ kibana_server_name }}"
    -days 365
    -keyout /etc/ssl/private/apache.key
    -out /etc/ssl/certs/apache.cert
    -extensions v3_ca
    creates=/etc/ssl/certs/apache.cert
  when: kibana_self_signed is defined and kibana_self_signed == true
  tags:
    - install

- name: Enable apache modules
  command: a2enmod "{{ item }}"
  with_items: "{{ kibana_apache_modules }}"
  tags:
    - install

- name: Template Kibana Apache Config
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/sites-available/{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - 000-kibana.conf
  notify: Restart Apache
  tags:
    - config_changed

- name: Drop Apache2 Ports File
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - ports.conf
  notify: Restart Apache
  tags:
    - config_changed

- name: Link Kibana Site
  file:
    state: "link"
    src: "/etc/apache2/sites-available/000-kibana.conf"
    dest: "/etc/apache2/sites-enabled/000-kibana.conf"
    owner: "root"
    group: "root"
  notify: Restart Apache
  tags:
    - config_changed

- name: Remove Apache Default Site
  file:
    state: "absent"
    path: "/etc/apache2/sites-enabled/000-default.conf"
  notify: Restart Apache
  tags:
    - config_changed

- name: Create kibana http_auth user
  htpasswd:
    path: "/etc/apache2/users"
    name: "{{ kibana_web_login }}"
    password: "{{ kibana_web_password }}"
    owner: "root"
    group: "www-data"
    mode: "0640"
    create: "yes"
    state: "present"
  notify: Restart Apache
  tags:
    - config_changed
