- name: Create ElasticSearch scripts directory
  file:
    path: /etc/elasticsearch/scripts
    state: directory
    owner: "{{ elasticsearch_system_user }}"
    group: "{{ elasticsearch_system_group }}"
    mode: 0755
  tags:
    - install

- name: Deploy ElasticSearch configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/elasticsearch/{{ item }}"
    owner: "{{ elasticsearch_system_user }}"
    group: "{{ elasticsearch_system_group }}"
  with_items:
    - elasticsearch.yml
    - logging.yml
  notify:
    - Restart ElasticSearch
  tags:
    - install
    - config_changed

- name: Deploy ElasticSearch service configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/default/{{ item }}"
    owner: "{{ elasticsearch_system_user }}"
    group: "{{ elasticsearch_system_group }}"
  with_items:
    - elasticsearch
  notify:
    - Restart ElasticSearch
  tags:
    - install

- name: Ensure proper permissions for index dir
  file:
    path: "/var/lib/elasticsearch/{{ elasticsearch_cluster}}"
    state: "directory"
    owner: "{{ elasticsearch_system_user }}"
    group: "{{ elasticsearch_system_group }}"
    recurse: "yes"

- name: Restart ElasticSearch before proceeding
  meta: flush_handlers

- name: Wait for ElasticSearch port
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ elasticsearch_http_port }}"
  tags:
    - install
