- name: Create ElasticSearch Curator directory
  file:
    path: "{{ elasticsearch_curator_config_dir }}"
    state: directory
    owner: "{{ elasticsearch_system_user }}"
    group: "{{ elasticsearch_system_group }}"
    mode: 0755
  tags:
    - install

- name: Deploy Elasticsearch Curator Configuration Files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ elasticsearch_curator_configuration_files }}"
    - "{{ elasticsearch_curator_action_files }}"
  tags:
    - install

- name: Setup the ElasticSearch Curator cron job
  cron:
    name: "ElasticSearch Curator"
    minute: 0
    hour: 1
    user: root
    job: /usr/local/bin/curator --config {{ elasticsearch_curator_config_file }} {{ elasticsearch_curator_action_file }}
    cron_file: "elasticsearch_curator"
  tags:
    - install
