#!/bin/bash
# Newer Ubuntu version may not have python2 installed by default.  Check
# and install the required packages.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml' 'dnspython')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

# Now do the actual install
exec ./hooks/install.real
