---
kibana_root: /opt/kibana

kibana_pre_packages:
  - apt-transport-https
  - wget
  - curl
  - rsync
  - apache2
  - python-passlib
  - python-pip
  - unzip
  - haproxy

kibana_apache_modules:
  - rewrite
  - ssl
  - proxy
  - proxy_http

kibana_pip_packages:
  - httplib2

kibana_verbose: True

# This is the user:group that kibana runs as
kibana_service_user: kibana
kibana_service_group: root

kibana_server_name: "{{ ansible_hostname }}"
kibana_self_signed: true
kibana_log_level: info
kibana_ssl_cert: '/etc/ssl/certs/apache.cert'
kibana_ssl_key: '/etc/ssl/private/apache.key'
kibana_ssl_cert_path: '/etc/ssl/certs'
kibana_ssl_protocol: '{{ ssl_protocol|default("ALL -SSLv2 -SSLv3") }}'
kibana_ssl_cipher_suite: '{{ ssl_cipher_suite|default("ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS") }}'

apache_log_dir: /var/log/apache2

apache_service: apache2

config_dir: "{{ kibana_root }}/config"

temp_install_directory: /tmp/kibana_install

kibana_directory: kibana-5.6.2-linux-x86_64
kibana_package:
    { url: "https://artifacts.elastic.co/downloads/kibana",
      file: "kibana-5.6.2-linux-x86_64.tar.gz",
      checksum: "sha512:e9ef4f8dee16b1274d4b0399c0df938a5c99d450f8b8f8b1e56b3410661696b67a100187aa719c270359bd22b000dc5002c664d33eb178fd657dc80ae8237830" }

#To find the nodejs version used by kibana goto
#https://github.com/elastic/kibana/blob/master/.node-version
#And select the tag for the version of kibana used.
nodejs_version: v6.11.1
nodejs_directory: node-{{ nodejs_version }}-linux-{{ ansible_architecture }}
nodejs_package:
    { url: "http://nodejs.org/dist/{{ nodejs_version }}",
      file: "node-{{ nodejs_version }}-linux-{{ ansible_architecture }}.tar.gz" }

kibana_version: 5.6.2
