elasticsearch_system_user: elasticsearch
elasticsearch_system_group: elasticsearch

elasticsearch_pip_packages:
  - elasticsearch
  - elasticsearch-curator

# Change this to 'true' will ensure that elasticsearch never uses swap space
elasticsearch_bootstrap_memory_lock: "false"

# Change this to override the default value (which is 50% of total memory)
# elasticsearch_heap_size_mb: 1024

# Change this to override the default value (which is the same value as
# elasticsearch_heap_size_mb). if mlockall is set to true this setting
# is intentionally set to 'unlimited' instead.
# elasticsearch_max_locked_memory_mb: 1024

# Note that this effectively disables the distributed features
# If you're expanding beyond one node these should be adjusted
elasticsearch_index_number_of_shards: 1
elasticsearch_index_number_of_replicas: 0

elasticsearch_curator_logstash_prune_days: 60
elasticsearch_curator_metricbeat_prune_days: 30
elasticsearch_curator_config_dir: /etc/curator
elasticsearch_curator_config_file: "{{ elasticsearch_curator_config_dir }}/curator.yml"
elasticsearch_curator_action_file: "{{ elasticsearch_curator_config_dir }}/curator_action.yml"

elasticsearch_curator_configuration_files:
  - { src: "curator.yml.j2", dest: "{{ elasticsearch_curator_config_file }}" }

elasticsearch_curator_action_files:
- { src: "curator_action.yml.j2", dest: "{{ elasticsearch_curator_action_file }}" }

elasticsearch_pre_packages:
  - apt-transport-https
  - wget
  - curl
  - rsync
  - python-pip
  - openjdk-8-jre-headless

#for ppc64le and x86 use the deb package to install
elasticsearch_packages:
  - { url: "https://artifacts.elastic.co/downloads/elasticsearch",
      file: "elasticsearch-5.6.2.deb",
      checksum: "sha512:6e1ce8f4ad957a1cd70e016c7821a71187a451bf4377c84dbbbc2d8a67ac4fc06de859c1640e25432d4d54ff5f5bdb417a49b9ef14d1d245dd8d161a14e5bd3b" }

elasticsearch_version: 5.6.2
