deb_package_architecture: ppc64el

build_prereq_packages:
  - git
  - build-essential

build_dir: /tmp/filebeat_build

go_download: https://storage.googleapis.com/golang/go1.7.6.linux-{{ ansible_architecture }}.tar.gz
go_root: "{{ build_dir }}/go"
go_path: "{{ build_dir }}/go_path"

beats_path: "{{ go_path}}/src/github.com/elastic/beats"
beats_url: https://github.com/elastic/beats.git
beats_tag: v5.6.2
filebeat_dir: "{{ beats_path }}/filebeat"

go_daemon_dir: "{{ build_dir }}/go_daemon"
go_daemon_url: https://github.com/tsg/go-daemon.git
go_daemon_build_cmd: "cc god.c -m64 -o god-linux-{{ ansible_architecture }} -lpthread -static"

package_path_host: "/tmp"

deb_package_amd64: filebeat-5.6.2-amd64.deb
deb_package_target_platform: filebeat-5.6.2-{{ ansible_architecture }}.deb
deb_download_path: https://artifacts.elastic.co/downloads/beats/filebeat
deb_download_checksum: "sha512:2b740fc2d30a95212daf062157f39c1ad05a96c5cf3dd1a68c03d0f00bafb37e376351cd8fb0ea70688e827cad0fe77df37ed5dd23ae4161107ee767bed9d71a"
deb_working_dir: "{{ build_dir }}/debworkingdir"
deb_binary_path: "{{ deb_working_dir }}/usr/share/filebeat/bin"
deb_control_file: "{{ deb_working_dir }}/DEBIAN/control"
deb_md5sums_file: "{{ deb_working_dir }}/DEBIAN/md5sums"

