options:
  kibana_app_port:
    type: int
    default: 5601
    description: "http port and internal communication port"
  kibana_ssl_port:
    type: int
    default: 8444
    description: "https port"
  kibana_web_login:
    type: string
    default: kibana
    description: "Default userid for the web interface"
  kibana_web_password:
    type: string
    default: kibana
    description: "Password for the default userid for the web interface"
  frontend_port:
    type: int
    default: 9205
    description: |
      Unused port to be used to frontend haproxy on localhost to multiple
      backend elasticsearch servers and ports.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup

